"""empty message

Revision ID: 2723ded5d35c
Revises: 6a2024c0d196
Create Date: 2025-12-06 17:59:19.299038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2723ded5d35c'
down_revision = '6a2024c0d196'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('programme_exercices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exercice_name', sa.String(length=200), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('programme_exercices', schema=None) as batch_op:
        batch_op.drop_column('exercice_name')

    # ### end Alembic commands ###
