"""Initial tables

Revision ID: 6a2024c0d196
Revises: 
Create Date: 2025-11-23 12:13:30.870071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a2024c0d196'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('programmes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('km', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('programme_exercices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('programme_id', sa.Integer(), nullable=False),
    sa.Column('exercice_id', sa.Integer(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['programme_id'], ['programmes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('station_depart_id', sa.Integer(), nullable=False),
    sa.Column('station_arrivee_id', sa.Integer(), nullable=False),
    sa.Column('heure_depart', sa.Time(), nullable=False),
    sa.Column('heure_arrivee', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['station_arrivee_id'], ['stations.id'], ),
    sa.ForeignKeyConstraint(['station_depart_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trains')
    op.drop_table('programme_exercices')
    op.drop_table('stations')
    op.drop_table('programmes')
    # ### end Alembic commands ###
